import os

DATA_CSV = os.path.join('.', 'IMDBDataset.csv')
EPOCHS = 32
LR_BERT = 0.001
LR_CLASSIFIER = 0.00001
MAX_SEQ_LEN = 128
PRETRAINED_WEIGHTS = 'bert-base-uncased'
SCHED_DECAY = 0.1
SCHED_STEP_SIZE = 3
TRAIN_BATCH_SIZE = 16
TEST_BATCH_SIZE = 32
VAL_SPLIT = 0.1
